image: awinia/node14-npm7-angular12-chrome:latest

variables:
  ErrorActionPreference: stop

cache:
  paths:
    - node_modules
    - dist
  policy: push-pull

stages:
  - setup
  - lint
  - build
  - test

setup:
  stage: setup
  script:
    - npm ci
  tags:
    - docker

lint:
  needs: ["setup"]
  stage: lint
  script:
    - ng lint shared
    - ng lint tcc-dashboard
    - ng lint msct-webui
  tags:
    - docker

build:
  needs: ["setup"]
  script:
    - ng build shared
    - ng build msct-webui
    - ng build tcc-dashboard
  tags:
    - docker

test:
  stage: test
  needs: ["build"]
  script:
    - ng test shared --watch false --progress false --code-coverage true --browsers ChromeCi
    - ng test msct-webui --watch false --progress false --code-coverage true --browsers ChromeCi
    - ng test tcc-dashboard --watch false --progress false --code-coverage true --browsers ChromeCi
  tags:
    - docker
